
version: '2'

services:
  web:
    container_name: web
    image: nginx:latest

    ports:
     - "80:80"
    volumes:
    - ./Main-Implemented:/app
    - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf

  phpfpm:
    container_name: phpfpm
    image: nattaponra/php-fpm:7.1
    volumes:
    - ./Main-Implemented:/app

