
version: '2'

services:
  web:
      container_name: web
      image: nattaponra/nginx:1.12
      ports:
      - 80:8080
      volumes:
      - ./docker/nginx:/bitnami/nginx/
      - ./Main-Implemented:/app


  phpfpm:
      container_name: phpfpm
      image: nattaponra/php-fpm:7.1
      volumes:
      - ./Main-Implemented:/app

